config/routes.rb
Matric::Application.routes.draw do

  root :to => "calculate#index"

  match "var/:id" => "calculate#var", :as => :var, :via => [:get, :post]
  match "mat/:id" => "calculate#matrix", :as => :mat, :via => [:get, :post]

  match "save" => "calculate#save",
        :defaults => { :format => 'text' }, :as => :save

  match "load" => "calculate#load", :as => :load, :via => [:get, :post]

  match "test/setup" => "test#setup", :as => :test_setup, :via => [:get, :post]
  match "test/q" => "test#test", :as => :test_question, :via => [:get, :post]

  match "help" => "calculate#help", :as => :help, :via => [:get]

  get "test/setup"

  get "calculate/index"

  get "calculate/matrix"

  get "calculate/var"

  get "calculate/save"

end

app/controllers/calculate_controller.rb
class CalculateController < ApplicationController
  include CalculateHelper

  def index
    
    flash[:msg] = ""
    case params[:commit]
    when "Calculate"
      if @calc.parse(params[:calc])
        flash[:msg] << "Parse Successful! ... "
        flash[:type] = "notice"
        begin
          @final_expr = @calc.calculate
          append = "Calculation Successful!"
          
        rescue SingularMatrixError
          append = "Calculation Successful!"
          
          @final_expr = Steps["No Final Answer. Attempted to invert singular matrix.", nil, @calc.subd_calc.steps ]
          
        rescue => $error
          append = "Calculation failed!"
          flash[:type] = "error"
        end
        
        flash[:msg] << append
      else
        
        flash[:msg] << "Parse Failure! ... "
        flash[:type] = "error"
      end
    end
    
    respond_to do |format|
      format.html
      format.js { render "calculation.js.erb" }
    end
  end

  def matrix
    @mat = params[:id]

    @verb = params[:commit]

    case @verb
    when "Save"
      if params[:_dim_x] && params[:_dim_y]
        d = Dimension.new(params[:_dim_x].to_i, params[:_dim_y].to_i)
        
        rows = []
        d.y.times { rows << [] }
        
        d.y.times do |j|
        d.x.times do |i|
          if (elem = parse_element(params[:"val-#{i},#{j}"]))
            rows[j][i] = elem
          else
            flash[:msg] = "Save Failed!"
            flash[:type] = "error"
          end
        end
        end
        
        @calc.add_matrix @mat, *rows unless flash[:type] == "error"
        
        flash[:msg] ||= "Save Successful!"
        flash[:type] ||= "notice"
     
      end
    when "Clear"
      
      @calc.clear_matrix @mat
      
      flash[:msg] = "Clear Successful!"
      flash[:type] = "notice"
      
      d = Dimension.new(params[:_dim_x].to_i, params[:_dim_y].to_i)
      rows = []
      d.y.times { rows << [""]*d.y }
      mat = Matrix[ *rows ]
      
    when "Confirm" # Dimension change
      @d = Dimension.new(params[:dim_x].to_i, params[:dim_y].to_i)
    end

    # Variables specific to Save/Clear

    mat ||= @calc.mats[@mat.to_sym] ? @calc.mats[@mat.to_sym].val : nil
    d   ||= @calc.mats[@mat.to_sym] ? mat.dim : Dimension.new(0,0)
    
    @fields = {}
    @type = "mat"
    
    d.y.times do |j|
    d.x.times do |i|
      @fields["field-#{i}_#{j}"] = mat[i,j] rescue ""
    end
    end
    
    # Variables Specific to New/Resize
    
    if @calc.mats[@mat.to_sym]
      @d ||= @calc.mats[@mat.to_sym].val.dim
    else
      @d ||= Dimension.new(2,2)
    end

    @mat_val = @calc.mats[@mat.to_sym] ? resize_mat(@calc.mats[@mat.to_sym].val, @d) : nil

    respond_to do |format|
      format.html
      format.js { render "update_sym.js.coffee.erb" }
    end
  end


  def var
    @var = params[:id]

    @verb = params[:commit]

    case @verb
    when "Save"
      if params[:val] && is_numeric(params[:val])
        v = params[:val]
        val = v.to_f == v.to_i ? v.to_i : v.to_f
        @calc.add_var @var, val

        flash[:msg]  = "Save Successful!"
        flash[:type] = "notice"
      else

        flash[:msg]  = "Save Failed!"
        flash[:type] = "error"
      end
    when "Clear"
      @calc.clear_var @var

      flash[:msg]  = "Clear Successful!"
      flash[:type] = "notice"
    end

    @fields = Hash["field-1", @calc.vars[@var.to_sym]]
    @type = "var"

    respond_to do |format|
      format.html
      format.js { render "update_sym.js.coffee.erb" }
    end
  end

  def save

    respond_to do |format|
      format.text do
        t = Time.now

        send_data @calc.save_state, 
                  :filename => "matric-state-#{t.strftime('%d%m%y')}.txt"

        return
      end
    end
  end
  
  def load
    
    if params[:commit] == "Load" && params[:state]
      
      #begin
        
          contents = params[:state][:file].read
          
          if validate_state_file contents
            @calc.load_state contents
            flash[:msg]  = "Loaded State From File Successfully!"
            flash[:type] = "notice"
          end
        
      #ensure
        
        flash[:msg]  ||= "Failed to Load Sate From File!"
        flash[:type] ||= "error"
        
      #end
      
    end
    
    respond_to do |format|
      format.html
    end
  end

  def help
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

end

app/helpers/calculate_helper.rb
module CalculateHelper

  def is_numeric x
    /^\-?\d+(?:\.\d+)?$/ =~ x
  end
  
  def parse_element x
    c = Calculation.new
    if c.parse(x)
      return c.subd_calc.simplify
    else
      return nil
    end
  end
  
  def unparse_element x
    x_str = x.to_s
    
    x_str.gsub!(/\^/, "**")
    
    pattern = Regexp.union( 
    /[a-z\)]\d+(?:\.\d+)?[a-z\(]/ , 
    /[a-z\)][\d\(]/ , 
    /[\d\)][a-z]/ )
    
    x_str.gsub!( pattern ) do |chars|
      chars.split("").join("*")
    end
    
    x_str.gsub!(/[a-z]+/){ |c| c.split("").join("*") }
    
    x_str
  end
  
  def resize_mat mat, d
    return nil if mat.nil?
    
    rows = []
    
    d.y.times { rows << [] }
    
    d.y.times do |j|
    d.x.times do |i|
    
      rows[j][i] = (mat[i,j] ? mat[i,j] : 0) rescue 0
        
    end
    end
    
    return Matrix[ *rows ]
  end
  
  def display_step step

      step_string = "" 

      step_string << "<div class=\\'instruction\\'>"
      step_string << step.instructions                         if step.instructions
      step_string << " <a class=\\'show-step\\'>Show Further Steps</a>" if step.further_steps && step.further_steps != []
      step_string << "</div>"

      if step.result
        step_string << "<div class=\\'answer\\'>"
        step_string << "<pre>#{step.result.gsub(/\n/, '<br/>')}</pre>"
        step_string << "</div>"
      end

      if step.further_steps && step.further_steps != []
        step_string << "<div class=\\'further-step\\'>"
        step_string << step.further_steps.map { |step| display_step(step) }.join("")
        step_string << "</div>"
      end

      step_string
    end
  
  def validate_state_file contents
    return false if /^(?:.*\n){52}$/ !~ contents
    contents.split("\n")[0...26].map { |x| x == "" || !(is_numeric x).nil? }.inject(true) { |t,b| t && b }
  end
  
end

app/views/calculate/_variable_pane.html.erb
<div id="pane">
  <ul id="pane-1" class="accordian startOpen">

	<li><a>Ans</a><span class="val" id="ans" ><%= truncate( @calc.ans.to_s, :length => 12 ) %></span></li>
	<li><a>Variables</a>
	  <ul>
		<% ('a'..'z').each do |c| %>
		<% val = @calc.vars[c.to_sym].nil? ? "" : @calc.vars[c.to_sym] %>
		<li>
		  <%=link_to(c, var_path(c))%>
		  <span class="val" id="var-<%=c%>"><%= truncate(val.to_s, :length => 25) %></span>
		</li>
		<% end %>
	  </ul>
	</li>
	<li><a>Matrices</a>
	  <ul>
		<% ('A'..'Z').each do |c| %>
		<% mat = @calc.mats[c.to_sym].nil? ? "" : @calc.mats[c.to_sym] %>
		<li>
		  <%=link_to(c, mat_path(c))%>
		  <span class="val" id="mat-<%=c%>"><%= truncate(mat.to_s, :length => 25) %></span>
		</li>
		<% end %>
	  </ul>
	</li>
  </ul>

</div>

app/views/calculate/calculation.js.erb
<% if $error %>
$('#error').html("<em>Error Details</em><p><%= $error.to_s.gsub(/\n/, '<br />').html_safe %></p>");
$('#error').slideDown('normal');
<% $error = nil %>
<% else %>
$('#error').slideUp('normal');
<% end %>

$('#ans').html('<%= truncate(@calc.ans.to_s, :length => 12 ) %>');

answer = $('#answer-area');

answer.slideUp('normal');

<% if @final_expr %>
$('#answer-area').html("<%= display_step(@final_expr).html_safe %>");
<% end %>

$('.show-step').click(function(){
	
	if( $(this).html() == "Show Further Steps") {
		$(this).parent().next().next().slideDown('normal');
		$(this).parent().next().slideUp('normal');
		$(this).html("Hide Further Steps");
	} else {
		$(this).parent().next().next().slideUp('normal');
		$(this).parent().next().slideDown('normal');
		$(this).html("Show Further Steps");
	}
});

<% unless flash[:type] == "error" %>
answer.slideDown('normal');
<% end %>

flash = $('#flash');

flash.removeClass().addClass('<%= flash[:type] %>');
flash.html('<%= flash[:msg] %>');
flash.slideDown('normal');

app/views/calculate/help.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Matric - Help</title>
	<%= stylesheet_link_tag "application" %>
</head>
<body>
<div id="help">
	<h2 id="top">Contents</h2>
	<ul>
		<li><a href="#operators">Operators</a></li>
		<li><a href="#functions">Functions</a></li>
		<li><a href="#variables">Variables</a></li>
		<li><a href="#matrices">Matrices</a></li>
		<li><a href="#generators">Generators</a></li>
	</ul>
	
	<div id="operators">
		<h2>Operators - <a href="#top">top</a></h2>
		<p>
			The following operators are available in Matric:
		</p>
		<table>
			<tr><td>Addition</td><td>+</td></tr>
			<tr><td>Subtraction</td><td>-</td></tr>
			<tr><td>Multiplication</td><td>*</td></tr>
			<tr><td>Division</td><td>/</td></tr>
			<tr><td>Exponentiation</td><td>**</td></tr>
		</table>
		<p>
			All the above operators are binary, meaning they must take two
			operands, or they will produce an error.
		</p>
		<p>
			The first two operators can operate on both matrices and scalar
			values, but they must be applied to two matrices, or two scalars
			not a matrix and a scalar.
		</p>
		<p>
			The third operator (*) can be applied to matrices and scalars
			interchangeably, and together (i.e. scalar multiplication of
			matrices is possible.).
		</p>
		<p>
			In the fourth operator (/), only scalar values can be used. And
			in the fifth operator (**), matrices can only be present in the
			left operand.
		</p>
	</div>
	
	<div id="functions">
		<h2>Functions - <a href="#top">top</a></h2>
		<p>
			The system provides certain functions for working with matrices:
		</p>
		<table>
			<tr>
				<td>trn(A)</td>
				<td>Matrix Transposition</td>
				<td>Converts every row in the matrix to a column, and vice
					versa, returning another matrix</td>
			</tr>
			<tr>
				<td>cofactors(A)</td>
				<td>Cofactor Matrix</td>
				<td>Replaces every element with its cofactor from the original
					matrix, returning another matrix</td>
			</tr>
			<tr>
				<td>det(A)</td>
				<td>Determinant</td>
				<td>Calculates the determinant of a provided matrix, returning
					a numeric value</td>
			</tr>
			<tr>
				<td>inverse(A)</td>
				<td>Matrix Inverse</td>
				<td>Produces the matrix that, when multiplied with the
					provided matrix, creates an identity matrix</td>
			</tr>
		</table>
		<p>
			Functions are applied by typing their name, followed by
			parentheses, containing the matrix they should act upon:
		</p>
			<pre>inverse( A )</pre>
		<p>	
			Caution should be taken, as function names are <em>case
			sensitive</em>, that is to say a function named "Inverse"
			differs from the (actual) function "inverse".
		</p>
	</div>
	
	<div id="variables">
		<h2>Variables - <a href="#top">top</a></h2>
		<p>
			There are a variety of variables that can be used to either
			substitute values in to a calculation or to perform symbolic
			manipulation:
		</p>
		<table>
			<tr>
				<td>Ans</td>
				<td>A special symbol that can be used to substitute the
					answer from the previous calculation in to the current
					one.</td>
			</tr>
			<tr>
				<td>a..z</td>
				<td>The lowercase characters 'a' through 'z' each stand for a
					variable that could contain a numeric value.</td>
			</tr>
			<tr>
				<td>A..Z</td>
				<td>The uppercase characters 'A' to 'Z' are likewise used to
					represent a matrix</td>
			</tr>
		</table>
		<p>
			As symbols represent numeric values (scalar or matric), they can be
			used anywhere a numeric value would be allowed. If a value has
			been assigned to one of the variables in the variable pane 
			(left of calculation pane), then this value is substituted
			in place of the symbol when the calculation takes place. If,
			however, there is no value assigned to the symbol, the
			system will attempt to simplify the calculation as much as
			possible while still containing symbols. This is how the system
			deals with both lowercase, 'variable' symbols, and uppercase
			'matrix' symbols.
		</p>
	</div>
	
	<div id="matrices">
		<h2>Matrices - <a href="#top">top</a></h2>
		<p>
			As described in the above <a href="#variables">Variables</a>
			section, matrices can be represented as symbols that will be later
			substituted in to the calculation, which is useful for matrices
			that you wish to use multiple times, however, for matrices that are
			simply required for one calculation, an anonymous, or constant
			matrix can be written straight into the calculation.
		</p>
		<p>
			The syntax for an anonymous matrix is as follows:<br/>
			A list of elements enclosed in square brackets, delimited by commas,
			themselves delimited by commas and enclosed in square brackets. E.g.
			the anonymous matrix:
		</p>
		<pre>[[1,2],[3,4]]</pre>
		<p>
			Will produce the following matrix:
		</p>
		<pre>
+---+---+
| 1 | 2 |
| 3 | 4 |
+---+---+</pre>

		<p>
			Anonymous matrices may contain expressions and symbols as elements,
			just like matrices assigned to symbols
		</p>
	</div>
	
	<div id="generators">
		<h2>Generators - <a href="#top">top</a></h2>
		<p>
			There are certain key matrices that hold particular significance.
			For these such matrices, there are generator functions that make it
			simpler to use these commonly used matrices:
		</p>
		<table>
			<tr>
				<td>Matrix.identity(s)</td>
				<td>
					Produces an identity matrix of size <em>s</em>x<em>s</em>
				</td>
			</tr>
			<tr>
				<td>Matrix.zero(s)</td>
				<td>Produces the zero matrix of size <em>s</em>x<em>s</em></td>
			</tr>
			<tr>
				<td>Matrix.random(s,l)</td>
				<td>Generates a random integer matrix of size 
					<em>s</em>x<em>s</em> whose elements fall within the
					range of +<em>l</em> to -<em>l</em>.</td>
			</tr>
			<tr>
				<td>Matrix.nice(s,l)</td>
				<td>Generates a random integer matrix of size
					<em>s</em>x<em>s</em> whose elements fall within the range
					of +<em>sl<sup>2</sup></em> to <em>sl<sup>2</sup></em> that
					can be inverted to always produce another integer matrix.
					</td>
		</table>
		<p>
			These generator functions can be used anywhere a normal matrix would
			have been used, however, one restriction is that, unlike the
			aforementioned functions, they cannot accept symbols as arguments 
			(as an <em>a</em> sized identity matrix does not make rational sense
			in a calculation).
		</p>
	</div>
</div>
</body>
</html>

app/views/calculate/index.html.erb
<%= render "variable_pane" %>

<div id="flash"></div>

<div id="calculation-edit">
	<%= form_tag( root_path, :remote => true) do %>
		<%= text_area_tag :calc, "", :class => "symbol-input" %>
		<%= submit_tag "Calculate", :class => "button-normal" %>
	<% end %>
</div>
<div id="error"></div>
<div id="answer-area">
</div>

app/views/calculate/load.html.erb
<%= render "variable_pane"%>

<div id="flash" class="default-on <%= flash[:type] %>">
	<%= flash[:msg] %>
</div>

<div id="load-pane">
	<%= form_tag load_path, :multipart => true do %>
		<%= file_field :state, :file, :accept => "text/plain", :class => "symbol-input" %>
		
		<div id="buttons">
			<%= submit_tag "Load", :class => "button-normal" %>
			<%= link_to "Cancel", root_path, :class => "button-cancel" %>
		</div>
	<% end %>
</div>

app/views/calculate/matrix.html.erb
<%= render "variable_pane" %>

<div id="flash"></div>

<div id="sym-edit">
	
<div id="top-bar">
	<span id="instructions">Currently Editing: <span id="sym-name"><%= @mat %></span></span>
	
	<%= form_tag(mat_path(@mat)) do %>	
		<span id="dimensions">
			Dimensions 
			<% options_x = (1..10).map { |n| "<option #{'selected=\'selected\'' if n==@d.x}>#{n}</option>" }.join("").html_safe %>
			<% options_y = (1..10).map { |n| "<option #{'selected=\'selected\'' if n==@d.y}>#{n}</option>" }.join("").html_safe %>
			<%= select_tag :dim_x, options_x %>
			<%= select_tag :dim_y, options_y %>
			<%= submit_tag "Confirm", :class => "button-confirm" %>
		</span>
	<% end %>
</div>
	
<%= form_tag(mat_path(@mat), :remote => true) do %>

	<%= hidden_field_tag :_dim_x, @d.x %>
	<%= hidden_field_tag :_dim_y, @d.y %>

	<br/>
	<table id="matrix-table">
	  <% @d.y.times do |j| %>
		<tr>
		  <% @d.x.times do |i| %>
			<td> <%= text_field_tag "val-#{i},#{j}",
								   	unparse_element(@mat_val ? @mat_val[i,j] : ""), 
									:class => "symbol-input",
								   	:id => "field-#{i}_#{j}"%>
			</td>
		  <% end %>
		</tr>
	  <% end %>
	</table>
	
	<div id="buttons">
	  <%= submit_tag( "Save", :class => "button-normal" ) %>
	  <%= submit_tag( "Clear", :class => "button-warn" ) %>
	  <%= link_to "Cancel", root_path, :class => "button-cancel" %>
	</div>
<% end %>

</div>

app/views/calculate/save.html.erb
<h1>Calculate#save</h1>
<p>Find me in app/views/calculate/save.html.erb</p>

app/views/calculate/update_sym.js.coffee.erb
<% @fields.each do |field, contents| %>

$('#<%= field %>').val( '<%= unparse_element(contents) %>' )

<% end %>

field = '#'+'<%= @type %>'+'-'+'<%= @type == "var" ? @var : @mat %>'
value = '<%= truncate((@type == "var" ? @calc.vars[@var.to_sym].to_s : @calc.mats[@mat.to_sym].to_s), :length => 25) %>'

$(field).html(value)

flash = $('#flash')

flash.removeClass().addClass('<%= flash[:type] %>')
flash.html('<%= flash[:msg] %>')
flash.slideDown('normal')

app/views/calculate/var.html.erb
<%= render "variable_pane" %>

<div id="flash"></div>

<div id="sym-edit">

<div id="top-bar">
	<span id="instructions">Currently Editing: <span id="sym-name"><%= @var %></span></span>
</div>

<%= form_tag(var_path(@var), :remote => true) do %>
	<%= text_field_tag(:val, 
		@calc.vars[@var.to_sym], 
		:class => "symbol-input", :id => "field-1") %>
	
	<div id="buttons">
	  <%= submit_tag( "Save", :class => "button-normal" ) %>
	  <%= submit_tag( "Clear", :class => "button-warn" ) %>
	  <%= link_to "Cancel", root_path, :class => "button-cancel" %>
	</div>

<% end %>

</div>