config/routes.rb
Matric::Application.routes.draw do

  root :to => "calculate#index"

  match "var/:id" => "calculate#var", :as => :var, :via => [:get, :post]
  match "mat/:id" => "calculate#matrix", :as => :mat, :via => [:get, :post]

  match "save" => "calculate#save",
        :defaults => { :format => 'text' }, :as => :save

  match "load" => "calculate#load", :as => :load, :via => [:get, :post]

  match "test/setup" => "test#setup", :as => :test_setup, :via => [:get, :post]
  match "test/q" => "test#test", :as => :test_question, :via => [:get, :post]

  match "help" => "calculate#help", :as => :help, :via => [:get]

  get "test/setup"

  get "calculate/index"

  get "calculate/matrix"

  get "calculate/var"

  get "calculate/save"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  around_filter :wrap_sync
  before_filter :clear_flash_msg

  def wrap_sync
    sync_session
    yield
    sync_session
  end

  def sync_session
    @calc ||= session[:calc] || Calculation.new
    session[:calc] = @calc
  end

  def clear_flash_msg
    flash[:msg]  = nil
    flash[:type] = nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.erb
<div id="nav">
  <ul>
	<li><%= link_to "Calculate", root_path  %></li>
	<li><%= link_to "Test", test_setup_path %></li>
	<li><%= link_to "Save", save_path %></li>
	<li><%= link_to "Load", load_path %></li>
	<li><%= link_to "Help", help_path, :target => "_blank" %></li>
  </ul>
</div>